name: Docker build and push
description: Builds and pushes docker image

inputs:
  docker-username:
    description: 'Dockerhub username'
    required: true
  docker-password:
    description: 'Dockerhub password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get version
      id: get_version
      shell: bash
      run: |
        version=$(awk -F'"' '/^version =/ {print $2}' build.gradle.kts)
        gitHash=$(git rev-parse --short HEAD)
        fullVersion="$version"-"$gitHash"
        echo "it=""$fullVersion""" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build Docker image
      shell: bash
      run: docker build -t hsuliz/terraform-ansible-sample:${{ steps.get_version.outputs.it }} .

    - name: Push Docker image
      shell: bash
      run: docker push hsuliz/terraform-ansible-sample:${{ steps.get_version.outputs.it }}