---
- name: Configure new instance
  hosts: web-server
  become: yes
  pre_tasks:
    - name: Wait for the instance to be reachable
      ansible.builtin.wait_for:
        port: 22
        timeout: 300
        state: started
      delegate_to: localhost
      become: false

  roles:
    - install_docker