---
- name: Configure new instance
  hosts: web_server
  become: yes
  pre_tasks:
    - setup:
      register: setup_status
      until: setup_status is success
      delay: 10
      retries: 30

  roles:
    - install_docker