name: build

on:
  push:
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps. workflow-summary.outputs.artifact-name }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: 'gradle'

      - name: Lint
        run: ./gradlew ktfmtCheck

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Build
        run: ./gradlew buildFatJar

      - name: Version
        id: version-step
        if: github.ref_name == 'refs/heads/main'
        run: |
          echo 'version=$(./gradlew getVersion -q)' >> $GITHUB_OUTPUT
          echo 'git-hash=$(git rev-parse --short HEAD)' >> $GITHUB_OUTPUT

      - name: Upload artifact
        id: artifact-upload-step
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: web-server-${{ steps.version-step.outputs.version }}-${{ steps.version-step.outputs.git-hash }}-fat.jar
          path: build/libs/web-server-${{ steps.version-step.outputs.version }}-fat.jar
          if-no-files-found: error
          overwrite: true

      - name: Workflow summary
        id: workflow-summary
        if: github.ref_name == 'main'
        run: |
          
          echo "Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}" >> $GITHUB_STEP_SUMMARY
          echo "Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}" >> $GITHUB_STEP_SUMMARY

  push-to-registry:
    needs: [ build ]
    uses: ./.github/workflows/docker-build-push.yml