name: build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: 'gradle'

      - name: Lint
        run: ./gradlew ktfmtCheck --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Build
        run: ./gradlew buildFatJar --no-daemon

      - uses: ./.github/actions/docker-build-and-push
        if: github.ref_name == 'main'

        #run: |
        #  echo "version=$(./gradlew getVersion -q)" >> $GITHUB_OUTPUT
        #  echo "git-hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT



