name: build

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
          - monalisa
          - cschleiden

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build -x test --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon

  push-to-dockerhub:
    needs:
      - build-and-test
    runs-on: ubuntu-latest

