name: build

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: 'gradle'

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Build fat Jar
        run: ./gradlew buildFatJar --no-daemon

      - name: Get version
        id: version
        run: |
          VERSION=$(./gradlew getVersion -q)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: simple-automation-${{ steps.version.outputs.version }}.jar
          path: build/libs/simple-automation-all.jar