name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: 'gradle'

      - name: Lint
        run: ./gradlew ktfmtCheck

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Build
        run: ./gradlew buildFatJar

      - name: Version
        id: version-step
        if: github.ref == 'refs/heads/main'
        run: |
          echo "version=$(./gradlew getVersion -q)" >> $GITHUB_OUTPUT
          echo "git-hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        id: artifact-upload-step
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: web-server-${{ steps.version-step.outputs.version }}-${{ steps.version-step.outputs.git-hash }}-fat.jar
          path: build/libs/web-server-${{ steps.version-step.outputs.version }}-fat.jar
          if-no-files-found: error

      - name: Workflow summary
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}" >> $GITHUB_STEP_SUMMARY
          echo "Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}" >> $GITHUB_STEP_SUMMARY