name: docker-build-push

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Dockerfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
          sparse-checkout-cone-mode: false

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Check
        run: ls -l

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-automation:test-name .
