name: Onboard

on:
  workflow_dispatch:

jobs:
  Onboard:
    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_aws_vpc_id: ${{ secrets.AWS_VPC_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="bucket=simple-automation" \
            -backend-config="key=automation/terraform/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Add generated Ansible inventory
        run: mv terraform/inventory playbooks

      - name: Add ssh key to Ansible playbooks
        run: |
          mv terraform/oei-key-pair.pem playbooks/oei-key-pair.pem
          chmod 400 "playbooks/oei-key-pair.pem"

      - name: Ansible playbook
        working-directory: ./playbooks
        run: ansible-playbook -i inventory configure.yml

      - name: Save resources to S3 bucket
        run: |
          aws s3 cp playbooks/inventory s3://simple-automation/automation/ansible/inventory
          aws s3 cp playbooks/oei-key-pair.pem s3://simple-automation/automation/oei-key-pair.pem