name: Onboard

on:
  workflow_dispatch:

jobs:
  Onboard:
    #env:
    #  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
    #  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
    #  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
    #  TF_VAR_aws_vpc_id: ${{ secrets.AWS_VPC_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform apply
        id: terraform-apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get EC2 IP address
        run: echo "${{ steps.terraform-apply.outputs.ec2_ip }}"

