name: promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to promote'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: 'gradle'

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Increment version
        id: increment_version
        run: |
          NEW_VERSION=$(./gradlew incrementVersion --versionType=${{ github.event.inputs.version }} -q)
          echo "incremented_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Build fat Jar
        run: ./gradlew buildFatJar --no-daemon

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-automation:${{ steps.increment_version.outputs.incremented_version }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-automation:${{ steps.increment_version.outputs.incremented_version }}

      - name: Commit updated version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version update to ${{ steps.increment_version.outputs.incremented_version }}
