name: Promote

on:
  workflow_dispatch:

jobs:
  Promote:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get resources from S3 bucket
        run: |
          aws s3 cp playbooks/inventory s3://simple-automation/automation/ansible/inventory
          aws s3 cp playbooks/oei-key-pair.pem s3://simple-automation/automation/oei-key-pair.pem
          chmod 400 "playbooks/oei-key-pair.pem"

      - name: Ansible playbook promote run
        working-directory: playbooks
        run: ansible-playbook -i inventory configure.yml