name: promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to promote'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: 'gradle'

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Build fat Jar
        run: ./gradlew buildFatJar --no-daemon

      - name: Get version
        id: version
        run: |
          VERSION=$(./gradlew getVersion -q)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-automation:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-automation:latest
