name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to release'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: 'gradle'

      - name: Lint
        run: ./gradlew ktfmtCheck --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Build
        run: ./gradlew buildFatJar --no-daemon

      - name: Increment version
        id: increment-version
        run: |
          NEW_VERSION=$(./gradlew incrementVersion --versionType=${{ github.event.inputs.version }} -q)
          echo "incremented_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Mock deploy
        run: |
          docker search hsuliz/simple-automation

      - name: Commit updated version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version update to ${{ steps.increment_version.outputs.incremented-version }}
