name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to release'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  promote:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hsuliz
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest Docker image tag
        id: get-latest-docker-image-tag
        shell: bash
        run: |
          URL="https://registry.hub.docker.com/v2/repositories/hsuliz/simple-automation/tags"
          RESPONSE=$(curl -s "$URL")
          IMAGE_TAG=$(echo "$RESPONSE" | jq -r '.results[0].name')
          echo "it=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Get latest Docker image
        shell: bash
        run: |
          docker pull hsuliz/simple-automation:${{ steps.get-latest-docker-image-tag.outputs.it }}

      - name: Mock scan
        shell: bash
        run: |
          echo "mock scan"

      - name: Increment version
        id: increment-version
        run: |
          NEW_VERSION=$(./gradlew incrementVersion --versionType=${{ github.event.inputs.version }} -q)
          echo "incremented-version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Re-tag with new version
        shell: bash
        run: |
          docker tag hsuliz/simple-automation:${{ steps.get-latest-docker-image-tag.outputs.it }} hsuliz/simple-automation:${{ steps.increment-version.outputs.incremented-version }}

      - name: Push Docker image
        shell: bash
        run: docker push ${{ inputs.docker-username }}/simple-automation:${{ steps.increment-version.outputs.incremented-version }}

      - name: Commit updated version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version update to ${{ steps.increment-version.outputs.incremented-version }}
